version: "3.8"

services:
  next-app:
    container_name: next-app
    build:
      context: web
      dockerfile: Dockerfile.dev
    env_file:
      - ./web/.env
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - mod-mii-next-network

  # Add more containers below (nginx, postgres, etc.)

  minio:
    image: minio/minio:latest
    container_name: wii-homebrew-minio
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - mod-mii-next-network

  # Optional: Create bucket on startup
  createbuckets:
    image: minio/mc:latest
    container_name: minio-bucket-creator
    depends_on:
      - minio
    networks:
      - mod-mii-next-network
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/$S3_BUCKET_NAME;
      exit 0;
      "
    restart: "no"
  api:
    container_name: mod-mii-api-dev
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
    restart: always
    networks:
      - mod-mii-next-network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  mod-mii-next-network:

# Define volumes for persistent data storage
volumes:
  minio_data:
