version: "3.8"

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      - WINDOWS_IP=runner
    volumes:
      - temp_data:/mod-mii-next/.temp-downloads
      - ./public:/mod-mii-next/public
    restart: always
    networks:
      - mod-mii-next-network

  minio:
    image: minio/minio:latest
    container_name: wii-homebrew-minio
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - mod-mii-next-network

  # Optional: Create bucket on startup
  createbuckets:
    image: minio/mc:latest
    container_name: minio-bucket-creator
    depends_on:
      - minio
    networks:
      - mod-mii-next-network
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/$S3_BUCKET_NAME;
      exit 0;
      "
    restart: "no"

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  mod-mii-next-network:

# Define volumes for persistent data storage
volumes:
  minio_data:
  temp_data:
