version: "3.8"

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

  minio:
    image: minio/minio:latest
    container_name: wii-homebrew-minio
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - my_network

  # Optional: Create bucket on startup
  createbuckets:
    image: minio/mc:latest
    container_name: minio-bucket-creator
    depends_on:
      - minio
    networks:
      - my_network
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/$S3_BUCKET_NAME;
      exit 0;
      "
    restart: "no"

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true

# Define volumes for persistent data storage
volumes:
  minio_data:
