# syntax=docker.io/docker/dockerfile:1
FROM ubuntu AS deps

RUN apt-get update && apt-get install -y wget unzip wine \
    && wget https://github.com/modmii/modmii.github.io/releases/download/8.0.4/ModMii.zip \
    && unzip ModMii.zip -d /modmii \
    && rm ModMii.zip \
    && chmod +x /modmii/ModMii.exe

FROM node:20-alpine

WORKDIR /app

# Install Python dependencies
COPY --from=deps /modmii /modmii

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN corepack enable pnpm && pnpm i

COPY next.config.ts .
COPY tsconfig.json .
COPY components.json .
COPY postcss.config.mjs .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1


# Start Next.js in development mode based on the preferred package manager
CMD pnpm dev
