# syntax=docker.io/docker/dockerfile:1

FROM python:3 AS deps
WORKDIR /wiipy

RUN apt-get update && apt-get install -y git wget jq
RUN mkdir -p /modmii && \
    cd /modmii && \
    for url in $(curl -s https://api.github.com/repos/modmii/modmii.github.io/contents/Support/d2xModules | jq -r '.[] | select(.type=="file") | .download_url'); do \
      wget $url; \
    done

RUN ls -la /modmii 

RUN git clone https://github.com/NinjaCheetah/wiipy.git /wiipy
RUN pip install --no-cache-dir -r requirements.txt -t ./pip-packages

FROM node:20-alpine

WORKDIR /app

# Install Python dependencies
RUN apk add --no-cache python3 py3-pip
COPY --from=deps /wiipy /wiipy
COPY --from=deps /modmii /modmii
ENV PYTHONPATH=$PYTHONPATH:/wiipy/pip-packages

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN corepack enable pnpm && pnpm i

COPY next.config.ts .
COPY tsconfig.json .
COPY components.json .
COPY postcss.config.mjs .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1


# Start Next.js in development mode based on the preferred package manager
CMD pnpm dev
