# syntax=docker.io/docker/dockerfile:1
FROM ubuntu AS deps

RUN apt-get update && apt-get install -y wget unzip \
    && wget https://github.com/modmii/modmii.github.io/releases/download/8.0.4/ModMii.zip \
    && unzip ModMii.zip -d /modmii \
    && rm ModMii.zip \
    && chmod +x /modmii/ModMii.exe

FROM node:20

WORKDIR /app

# Install Wine dependencies
RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common wget gnupg2 apt-transport-https ca-certificates \
        xvfb xauth x11-utils \
        wine wine32 wine64 winbind cabextract\
        curl git unzip && \
    rm -rf /var/lib/apt/lists/*

# Set wine prefix
ENV WINEPREFIX=/wine
ENV WINEDEBUG=-all

RUN wineboot --init 

# Install winetricks manually and Visual C++ Redistributables (2015-2022)
# RUN wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -O /usr/local/bin/winetricks && \
#     chmod +x /usr/local/bin/winetricks && \
#     winetricks -q vcrun2022

# Install Python dependencies
COPY --from=deps /modmii /modmii

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN corepack enable pnpm && pnpm i

COPY next.config.ts .
COPY tsconfig.json .
COPY components.json .
COPY postcss.config.mjs .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1


# Start Next.js in development mode based on the preferred package manager
CMD pnpm dev
