import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { ArrowLeft, Github, Globe } from 'lucide-react';

export default function About() {
	return (
		<div className='min-h-screen bg-black p-4 font-sans sm:p-6'>
			<div className='mx-auto max-w-4xl'>
				<div className='space-y-6'>
					{/* What is this project */}
					<section className='rounded-lg border border-gray-700 bg-gray-900 p-6 shadow-sm'>
						<h2 className='mb-4 text-xl font-semibold text-white'>What is this project?</h2>
						<p className='mb-4 text-gray-300'>
							ModMiiNext aims to be a modern version of the original ModMii project But currently, it can analyze your
							Nintendo Wii console&apos;s system configuration and automatically provide the exact WAD files needed to
							update your system&apos;s homebrew components.
						</p>
						<p className='text-gray-300'>
							Simply upload your Wii&apos;s syscheck.csv file (generated by the{' '}
							<a
								href='https://wii.hacks.guide/syscheck.html'
								target='_blank'
								rel='noopener noreferrer'
								className='text-blue-400 hover:text-blue-300 hover:underline'
							>
								SysCheck
							</a>{' '}
							homebrew app), and this tool will analyze your system&apos;s current state, identify missing or outdated
							components, and provide a convenient ZIP download containing all the necessary WAD files for your specific
							system configuration.
						</p>
					</section>
					{/* Relationship to original ModMii */}
					<section className='rounded-lg border border-gray-700 bg-gray-900 p-6 shadow-sm'>
						<h2 className='mb-4 text-xl font-semibold text-white'>Connection to ModMii</h2>
						<p className='mb-4 text-gray-300'>
							This project is inspired by and builds upon the incredible work of{' '}
							<a
								href='https://modmii.github.io/'
								target='_blank'
								rel='noopener noreferrer'
								className='text-blue-400 hover:text-blue-300 hover:underline'
							>
								ModMii by XFlak
							</a>
							, the comprehensive Windows application that has been the go-to tool for Wii homebrew management since its
							inception.
						</p>
						<div className='mb-4 rounded-lg border border-gray-600 bg-gray-800 p-4'>
							<h3 className='mb-2 font-semibold text-white'>What is ModMii?</h3>
							<p className='text-sm text-gray-400'>
								ModMii is a powerful Windows application that can softmod any Wii, WiiU, or vWii console. It downloads
								all necessary files, generates custom guides, updates outdated homebrew, and performs many other Wii
								hacking functions including USB-loader setup and emulated NAND creation.
							</p>
						</div>
						<p className='text-gray-300'>
							While ModMii is an incredibly comprehensive desktop application, this web-based tool focuses specifically
							on the syscheck analysis and WAD file provision functionality, making it accessible from any device with a
							web browser.
						</p>
					</section>
					{/* Key differences and advantages */}
					<section className='rounded-lg border border-gray-700 bg-gray-900 p-6 shadow-sm'>
						<h2 className='mb-4 text-xl font-semibold text-white'>Why a web-based approach?</h2>
						<div className='grid gap-4 md:grid-cols-2'>
							<div className='rounded-lg border border-gray-600 bg-gray-800 p-4'>
								<h3 className='mb-2 font-semibold text-white'>✅ Advantages</h3>
								<ul className='space-y-1 text-sm text-gray-300'>
									<li>• Cross-platform compatibility (Windows, Mac, Linux)</li>
									<li>• No installation required</li>
									<li>• Always up-to-date</li>
									<li>• Handle download and handling of wad files in the backend</li>
								</ul>
							</div>
							<div className='rounded-lg border border-gray-600 bg-gray-800 p-4'>
								<h3 className='mb-2 font-semibold text-white'>📋 Current Scope</h3>
								<ul className='space-y-1 text-sm text-gray-300'>
									<li>• Focused on syscheck.csv analysis</li>
									<li>• Downloading of necessary WAD files from sources</li>
								</ul>
							</div>
						</div>
					</section>
					{/* How it works */}
					<section className='rounded-lg border border-gray-700 bg-gray-900 p-6 shadow-sm'>
						<h2 className='mb-4 text-xl font-semibold text-white'>How it works</h2>
						<div className='grid gap-4 md:grid-cols-3'>
							<div className='text-center'>
								<div className='mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full border border-gray-600 bg-gray-700'>
									<span className='text-lg font-bold text-white'>1</span>
								</div>
								<h3 className='mb-2 font-semibold text-white'>Upload Syscheck</h3>
								<p className='text-sm text-gray-300'>
									Upload your syscheck.csv file generated by the SysCheck Updater homebrew app on your Wii
								</p>
							</div>
							<div className='text-center'>
								<div className='mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full border border-gray-600 bg-gray-700'>
									<span className='text-lg font-bold text-white'>2</span>
								</div>
								<h3 className='mb-2 font-semibold text-white'>Analysis</h3>
								<p className='text-sm text-gray-300'>
									The server analyzes your console&apos;s configuration and identifies missing or outdated components.
									It then downloads the necessary WAD files from ModMii sources and stores them in a s3 for easy access.
								</p>
							</div>
							<div className='text-center'>
								<div className='mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full border border-gray-600 bg-gray-700'>
									<span className='text-lg font-bold text-white'>3</span>
								</div>
								<h3 className='mb-2 font-semibold text-white'>Download</h3>
								<p className='text-sm text-gray-300'>
									Get a customized ZIP file containing all the WAD files your system needs
								</p>
							</div>
						</div>
					</section>
					{/* Credits and links */}
					{/* Credits and links */}
					<section className='rounded-lg border border-gray-700 bg-gray-900 p-6 shadow-sm'>
						<h2 className='mb-4 text-xl font-semibold text-white'>Credits & Links</h2>
						<div className='space-y-4'>
							<div>
								<h3 className='mb-2 font-semibold text-gray-200'>Original ModMii Project</h3>
								<div className='flex flex-wrap gap-2'>
									<a
										href='https://modmii.github.io/'
										target='_blank'
										rel='noopener noreferrer'
										className='inline-flex items-center rounded-md border border-gray-600 bg-gray-800 px-3 py-1 text-sm text-gray-200 hover:bg-gray-700'
									>
										<Globe className='mr-1 h-3 w-3' />
										ModMii Website
									</a>
									<a
										href='https://github.com/modmii/modmii.github.io'
										target='_blank'
										rel='noopener noreferrer'
										className='inline-flex items-center rounded-md border border-gray-600 bg-gray-800 px-3 py-1 text-sm text-gray-200 hover:bg-gray-700'
									>
										<Github className='mr-1 h-3 w-3' />
										ModMii GitHub
									</a>
								</div>
								<p className='mt-2 text-sm text-gray-400'>
									Special thanks to XFlak and all ModMii contributors for their incredible work in the Wii homebrew
									community.
								</p>
							</div>
							<div>
								<h3 className='mb-2 font-semibold text-gray-200'>This Project</h3>
								<div className='flex flex-wrap gap-2'>
									<a
										href='https://github.com/jmischler72/mod-mii-next'
										target='_blank'
										rel='noopener noreferrer'
										className='inline-flex items-center rounded-md border border-gray-600 bg-gray-800 px-3 py-1 text-sm text-gray-200 hover:bg-gray-700'
									>
										<Github className='mr-1 h-3 w-3' />
										Source Code
									</a>
								</div>
								<p className='mt-2 text-sm text-gray-400'>
									Built with Next.js, TypeScript, and Tailwind CSS. Open source and available on GitHub.
								</p>
							</div>
						</div>
					</section>
					{/* Disclaimer */}
					<section className='rounded-lg border border-l-4 border-gray-700 border-l-yellow-500 bg-gray-900 p-6'>
						<h2 className='mb-4 text-xl font-semibold text-yellow-400'>⚠️ Important Disclaimer</h2>
						<div className='space-y-2 text-sm text-gray-300'>
							<p>
								<strong>This software comes with absolutely no warranty, neither stated nor implied.</strong> No one but
								yourself is to be held responsible for any damage this may cause to your console!
							</p>
							<p>
								<strong>Use this software at your own risk!</strong> Always make a NAND backup before modifying your Wii
								console.
							</p>
							<p>
								This is an independent project and is not officially affiliated with or endorsed by the original ModMii
								project or its developers.
							</p>
						</div>
					</section>{' '}
				</div>
			</div>
		</div>
	);
}
