'use client';

import { SyscheckFileUploadForm } from '@/components/syscheck-file-upload-form';
import { useState } from 'react';
import { UploadSyscheckData, UploadSyscheckResult } from '@/types/upload-syscheck-type';
import { Button } from '@/components/ui/button';
import { Archive, Info, HelpCircle, Download, Upload } from 'lucide-react';
import Link from 'next/link';
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from '@/components/ui/dialog';

export default function SyscheckPage() {
	const [uploadMessage, setUploadMessage] = useState<string>('');
	const [uploadData, setUploadData] = useState<UploadSyscheckData | null>(null);
	const [isCreatingArchive, setIsCreatingArchive] = useState<boolean>(false);
	const [isInstructionsOpen, setIsInstructionsOpen] = useState<boolean>(false);
	const [isWadInstructionsOpen, setIsWadInstructionsOpen] = useState<boolean>(false);

	const handleUploadSuccess = (result: UploadSyscheckResult) => {
		setUploadMessage(result.message || 'File uploaded successfully!');
		setUploadData(result.data || null);
		console.log('Upload successful:', result);
	};

	const handleUploadError = (error: string) => {
		setUploadMessage(`Error: ${error}`);
		setUploadData(null);
		console.error('Upload error:', error);
	};

	const handleDownloadArchive = async () => {
		if (!uploadData?.wadsInfos) {
			setUploadMessage('No files available for archive');
			return;
		}

		console.log('Creating archive with files:', uploadData.wadsInfos);
		setIsCreatingArchive(true);
		try {
			const response = await fetch('/api/wads/create-archive', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({
					wadnames: uploadData.wadsInfos.filter((file) => file.wadname !== undefined).map((file) => file.wadId),
				}),
			});

			if (!response.ok) {
				const errorData = await response.json();
				throw new Error(errorData.error || 'Failed to create archive');
			}

			// Extract download summary from response headers
			const downloadSummaryHeader = response.headers.get('X-Download-Summary');
			let summaryMessage = 'Archive downloaded successfully!';

			if (downloadSummaryHeader) {
				try {
					const summary = JSON.parse(downloadSummaryHeader);
					const totalFiles = summary.totalRequested;

					summaryMessage = `✅ Archive downloaded successfully!

📊 Download Summary:
• Total files requested: ${totalFiles}
• Downloaded: ${summary.downloaded} files
• Downloaded from S3: ${summary.cached} files
• Failed: ${summary.failed} files`;

					if (summary.failedFiles && summary.failedFiles.length > 0) {
						summaryMessage += `

❌ Failed files:
${summary.failedFiles.map((file: string) => `• ${file}`).join('\n')}`;
					}
				} catch (error) {
					console.error('Failed to parse download summary:', error);
				}
			}

			const blob = await response.blob();
			const url = window.URL.createObjectURL(blob);
			const a = document.createElement('a');
			a.href = url;
			a.download = 'wad-files.zip';
			document.body.appendChild(a);
			a.click();
			window.URL.revokeObjectURL(url);
			document.body.removeChild(a);

			setUploadMessage(summaryMessage);
		} catch (error) {
			console.error('Archive error:', error);
			setUploadMessage(`Error creating archive: ${error}`);
		} finally {
			setIsCreatingArchive(false);
		}
	};

	return (
		<div className='min-h-screen bg-black p-4 font-sans sm:p-6'>
			<main className='mx-auto max-w-6xl'>
				<div className='mb-8'>
					<h1 className='mb-4 text-3xl font-bold text-white'>Syscheck Analysis</h1>
					<div className='mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between'>
						<p className='mb-4 text-gray-300 sm:mb-0'>
							Upload your <span className='font-semibold'>syscheck.csv</span> file generated by the{' '}
							<Link
								href='https://wii.hacks.guide/syscheck.html'
								className='text-blue-400 underline hover:text-blue-300'
							>
								SysCheck Updater homebrew app
							</Link>{' '}
							on your Wii. This tool will analyze your console&apos;s configuration and provide you with a ZIP file
							containing all the necessary WAD files for your system.
						</p>

						<Dialog open={isInstructionsOpen} onOpenChange={setIsInstructionsOpen}>
							<DialogTrigger asChild>
								<Button variant='outline' className='flex shrink-0 items-center gap-2'>
									<HelpCircle className='h-4 w-4' />
									How to Generate Syscheck
								</Button>
							</DialogTrigger>
							<DialogContent className='max-h-[90vh] max-w-4xl overflow-y-auto'>
								<DialogHeader>
									<DialogTitle className='flex items-center gap-2'>
										<Info className='h-5 w-5 text-blue-400' />
										How to Generate a Syscheck File
									</DialogTitle>
									<DialogDescription>
										Follow these steps to create a syscheck.csv file on your Wii console.
									</DialogDescription>
								</DialogHeader>

								<div className='space-y-6 text-gray-300'>
									<div>
										<h3 className='mb-3 text-lg font-medium text-white'>Prerequisites</h3>
										<ul className='ml-4 list-inside list-disc space-y-2'>
											<li>A modded Wii console with the Homebrew Channel installed</li>
											<li>An SD card or USB drive</li>
											<li>Internet connection (optional, for easier download)</li>
										</ul>
									</div>

									<div>
										<h3 className='mb-3 text-lg font-medium text-white'>Installation Steps</h3>
										<ol className='ml-4 list-inside list-decimal space-y-3'>
											<li>
												<strong className='text-white'>Download SysCheck Updater:</strong>
												<ul className='mt-2 ml-6 list-inside list-disc space-y-1'>
													<li>
														Visit the{' '}
														<Link
															href='https://wii.hacks.guide/syscheck.html'
															className='text-blue-400 underline hover:text-blue-300'
														>
															official SysCheck guide
														</Link>{' '}
														or download directly from{' '}
														<Link
															href='https://oscwii.org/library/app/SysCheckME'
															className='text-blue-400 underline hover:text-blue-300'
														>
															oscwii.org
														</Link>
													</li>
													<li>
														Download the latest{' '}
														<code className='rounded bg-gray-800 px-2 py-1'>SysCheck_Updater_vX.X.X.zip</code> file
													</li>
												</ul>
											</li>

											<li>
												<strong className='text-white'>Install on SD Card/USB:</strong>
												<ul className='mt-2 ml-6 list-inside list-disc space-y-1'>
													<li>Extract the downloaded ZIP file</li>
													<li>
														Copy the <code className='rounded bg-gray-800 px-2 py-1'>SysCheck_Updater</code> folder to
														the <code className='rounded bg-gray-800 px-2 py-1'>apps</code> directory on your SD card or
														USB drive
													</li>
													<li>
														Your structure should look like:{' '}
														<code className='rounded bg-gray-800 px-2 py-1'>SD:/apps/SysCheck_Updater/</code>
													</li>
												</ul>
											</li>

											<li>
												<strong className='text-white'>Run SysCheck on Your Wii:</strong>
												<ul className='mt-2 ml-6 list-inside list-disc space-y-1'>
													<li>Insert your SD card or USB drive into your Wii</li>
													<li>Launch the Homebrew Channel from your Wii Menu</li>
													<li>
														Navigate to and launch <strong>SysCheck Updater</strong>
													</li>
													<li>Follow the on-screen prompts to generate the syscheck file</li>
													<li>
														The tool will create a <code className='rounded bg-gray-800 px-2 py-1'>syscheck.csv</code>{' '}
														file on your SD card/USB drive
													</li>
												</ul>
											</li>

											<li>
												<strong className='text-white'>Upload Your File:</strong>
												<ul className='mt-2 ml-6 list-inside list-disc space-y-1'>
													<li>Remove your SD card/USB drive from the Wii</li>
													<li>Insert it into your computer</li>
													<li>
														Locate the <code className='rounded bg-gray-800 px-2 py-1'>syscheck.csv</code> file (usually
														in the root directory)
													</li>
													<li>Upload it using the form below</li>
												</ul>
											</li>
										</ol>
									</div>
								</div>
							</DialogContent>
						</Dialog>
					</div>
				</div>

				{/* Upload Form Section */}
				<div className='rounded-lg border border-gray-700 bg-gray-900 p-6'>
					<SyscheckFileUploadForm
						onUploadSuccess={handleUploadSuccess}
						onUploadError={handleUploadError}
						className='mx-auto'
					/>
				</div>

				{uploadMessage && (
					<div
						className={`mt-2 rounded-lg p-3 ${uploadMessage.startsWith('Error') ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700'}`}
					>
						<p className='text-sm font-medium whitespace-pre-line'>{uploadMessage}</p>
					</div>
				)}

				{uploadData && (
					<div className='mt-4 grid gap-3 lg:grid-cols-2'>
						{/* Basic File Information */}
						<div className='rounded-lg bg-blue-50 p-3'>
							<h3 className='mb-2 text-sm font-semibold text-blue-900'>File Information</h3>
							<div className='space-y-1 text-xs text-blue-800'>
								<p>
									<strong>Filename:</strong> {uploadData.filename}
								</p>
								<p>
									<strong>Size:</strong> {(uploadData.size / 1024).toFixed(2)} KB
								</p>
							</div>
						</div>

						{/* System Information */}
						<div className='rounded-lg bg-green-50 p-3'>
							<h3 className='mb-2 text-sm font-semibold text-green-900'>System Information</h3>
							<div className='grid grid-cols-2 gap-1 text-xs text-green-800'>
								<p>
									<strong>Console:</strong> {uploadData.consoleType}
								</p>
								<p>
									<strong>Region:</strong> {uploadData.region}
								</p>
								<p>
									<strong>System Menu:</strong> {uploadData.systemMenuVersion}
								</p>
								<p>
									<strong>HBC:</strong> {uploadData.hbcVersion}
								</p>
								<p>
									<strong>Firmware:</strong> {uploadData.firmware.firmware}
								</p>
								<p>
									<strong>Version:</strong> {uploadData.firmware.firmwareVersion}
								</p>
							</div>
						</div>

						{/* System Status */}
						<div className='rounded-lg bg-yellow-50 p-3'>
							<h3 className='mb-2 text-sm font-semibold text-yellow-900'>System Status</h3>
							<div className='space-y-1 text-xs text-yellow-800'>
								<div className='flex items-center gap-2'>
									<span
										className={`h-2 w-2 rounded-full ${uploadData.systemChecks.isBootMiiInstalled ? 'bg-green-500' : 'bg-red-500'}`}
									></span>
									<span>BootMii: {uploadData.systemChecks.isBootMiiInstalled ? 'Installed' : 'Not Installed'}</span>
								</div>
								<div className='flex items-center gap-2'>
									<span
										className={`h-2 w-2 rounded-full ${uploadData.systemChecks.isPriiloaderInstalled ? 'bg-green-500' : 'bg-red-500'}`}
									></span>
									<span>
										Priiloader: {uploadData.systemChecks.isPriiloaderInstalled ? 'Installed' : 'Not Installed'}
									</span>
								</div>
								<div className='flex items-center gap-2'>
									<span
										className={`h-2 w-2 rounded-full ${!uploadData.systemChecks.isHbcOutdated ? 'bg-green-500' : 'bg-yellow-500'}`}
									></span>
									<span>HBC: {uploadData.systemChecks.isHbcOutdated ? 'Outdated' : 'Up to Date'}</span>
								</div>

								{uploadData.systemChecks.missingIOS.length > 0 && (
									<div className='mt-1'>
										<p className='font-medium'>Missing IOS:</p>
										<p className='text-xs'>{uploadData.systemChecks.missingIOS.join(', ')}</p>
									</div>
								)}

								{uploadData.systemChecks.outdatedD2XCios.length > 0 && (
									<div className='mt-1'>
										<p className='font-medium'>Outdated d2x cIOS:</p>
										<p className='text-xs'>{uploadData.systemChecks.outdatedD2XCios.join(', ')}</p>
									</div>
								)}
							</div>
						</div>

						{/* WAD Files */}
						{uploadData.wadsInfos && uploadData.wadsInfos.length > 0 && (
							<div className='rounded-lg bg-purple-50 p-3'>
								<div className='mb-2 flex items-center justify-between'>
									<h3 className='text-sm font-semibold text-purple-900'>
										Required WAD Files ({uploadData.wadsInfos.length})
									</h3>
									<div className='flex gap-2'>
										<Dialog open={isWadInstructionsOpen} onOpenChange={setIsWadInstructionsOpen}>
											<DialogTrigger asChild>
												<Button size='sm' variant='outline' className='flex items-center gap-1'>
													<Upload className='h-3 w-3' />
													Install Guide
												</Button>
											</DialogTrigger>
											<DialogContent className='max-h-[90vh] max-w-5xl overflow-y-auto'>
												<DialogHeader>
													<DialogTitle className='flex items-center gap-2'>
														<Upload className='h-5 w-5 text-green-400' />
														Install WADs - Complete Guide
													</DialogTitle>
													<DialogDescription>
														Official ModMii guide for installing WAD files using YAWM ModMii Edition
													</DialogDescription>
												</DialogHeader>

												<div className='space-y-6 text-gray-300'>
													{/* Video and Introduction */}
													<div className='text-center'>
														<div className='mb-4 flex justify-center'>
															<iframe
																width='480'
																height='270'
																src='https://www.youtube-nocookie.com/embed/eTODLzI_Hsk?rel=0'
																title='YAWM ModMii Edition Tutorial'
																frameBorder='0'
																allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'
																allowFullScreen
																className='rounded-lg'
															></iframe>
														</div>
														<p className='text-sm italic text-gray-400'>
															<strong>YAWM ModMii Edition</strong> stands for Yet Another Wad Manager ModMii Edition (aka yawmME). 
															A WAD Manager will allow you to install "WADs" containing things like updates and other content 
															for your console, like IOSs, custom IOSs (or cIOSs), or other downloadable content, which can 
															be all packed into WADs and installed to your console. Think of a WAD like a zip file but for the Wii.
														</p>
													</div>

													{/* Critical Warnings */}
													<div className='rounded-lg border border-red-700 bg-red-900/30 p-4'>
														<h4 className='mb-3 font-medium text-red-200'>⚠️ CRITICAL WARNINGS:</h4>
														<ul className='ml-4 list-inside list-disc space-y-1 text-sm text-red-100'>
															<li><strong>Do not unplug the console when installing WADs</strong></li>
															<li>WADs can be <u>uninstalled</u>, and if you're not careful you can brick your console by uninstalling or even installing the wrong WAD</li>
															<li>YAWM ModMii Edition has extra brick protection built in to restrict catastrophic actions like uninstalling System Menu WADs or required System Menu IOS</li>
															<li><strong>Stick to your ModMii guide and you'll be fine</strong></li>
														</ul>
													</div>

													{/* IOS/cIOS Information */}
													<div className='rounded-lg border border-blue-700 bg-blue-900/30 p-4'>
														<h4 className='mb-2 font-medium text-blue-200'>💡 What are IOSs and cIOSs?</h4>
														<div className='text-sm text-blue-100'>
															<p className='mb-2 italic'>
																"The Wii console uses the 'IOS' system to communicate with the hardware, it's like a driver 
																(compared to Windows). It contains information and communication tools (like how to access 
																the Disc drive, how to access USB, read the savegames data stored on internal memory, etc.)" ~Cyan
															</p>
															<p>
																If you're curious to learn more about IOSs or cIOSs, a thorough explanation can be found in{' '}
																<Link
																	href='https://gbatemp.net/threads/d2xl-cios-a-fork-of-davebaols-d2x-cios.558581/#post-8968173'
																	className='text-blue-300 underline hover:text-blue-200'
																	target='_blank'
																>
																	Cyan's IOS Explanation post
																</Link>
															</p>
														</div>
													</div>

													{/* Installation Steps */}
													<div>
														<h3 className='mb-4 text-lg font-medium text-white'>Installation Steps</h3>
														<ol className='ml-4 space-y-4 text-sm' style={{listStyleType: 'upper-alpha'}}>
															<li>
																<strong className='text-white'>On your console, load "YAWM ModMii Edition" from the HomeBrew Channel</strong>
															</li>
															
															<li>
																<strong className='text-white'>Choose your source device using left and right, most likely "Wii SD Slot", and Press <kbd className='rounded bg-gray-800 px-1'>A</kbd></strong>
															</li>

															<li>
																<div className='mb-2'>
																	<strong className='text-white'>Install your custom list of WADs found in the list below</strong>
																</div>
																<ul className='ml-4 list-inside list-disc space-y-1 text-gray-300'>
																	<li>Be careful not to install any additional WADs that may have been previously saved in this folder (they may be safe, but cannot be guaranteed)</li>
																</ul>
															</li>

															<li>
																<div className='mb-2'>
																	<strong className='text-white'>Hold <kbd className='rounded bg-gray-800 px-1'>+</kbd> for 2 seconds</strong> to select all the WADs in the folder
																</div>
																<ul className='ml-4 list-inside list-disc space-y-1 text-gray-300'>
																	<li>Alternatively, you can select or deselect your WADs individually by navigating to each one and hitting <kbd className='rounded bg-gray-800 px-1'>+</kbd></li>
																	<li><strong className='text-red-300'>Warning:</strong> do <u>not</u> use minus (-) as this will mark WADs for <u>uninstallation</u></li>
																</ul>
															</li>

															<li>
																<strong className='text-white'>After you've marked all the WADs listed below, press <kbd className='rounded bg-gray-800 px-1'>A</kbd> on any marked WAD to install them all</strong>
															</li>

															<li>
																<div className='mb-2'>
																	<strong className='text-white'>Confirm the total number selected for installation matches your WAD count, then press <kbd className='rounded bg-gray-800 px-1'>A</kbd> again to install</strong>
																</div>
																<ul className='ml-4 list-inside list-disc space-y-1 text-gray-300'>
																	<li>If any WADs fail to install properly please retry installing them</li>
																	<li>If asked whether to retain or remove Priiloader, <strong>press <kbd className='rounded bg-gray-800 px-1'>A</kbd> to retain Priiloader</strong></li>
																	<li>If you get error -1029 when attempting to install Mii-Channel-NUS-v6, carefully uninstall <u>only</u> this WAD using the minus <kbd className='rounded bg-gray-800 px-1'>-</kbd> button instead of <kbd className='rounded bg-gray-800 px-1'>+</kbd> before trying to install it again. Do NOT uninstall any other WADs unless you know what you are doing</li>
																</ul>
															</li>

															<li>
																<strong className='text-white'>After successfully installing all the WADs, press any button to continue, then press the <kbd className='rounded bg-gray-800 px-1'>Home</kbd> button on your Wiimote to exit YAWM ModMii Edition</strong>
															</li>
														</ol>
													</div>

													{/* Prerequisites */}
													<div className='rounded-lg border border-yellow-700 bg-yellow-900/30 p-4'>
														<h4 className='mb-2 font-medium text-yellow-200'>📋 Before You Begin:</h4>
														<ul className='ml-4 list-inside list-disc space-y-1 text-sm text-yellow-100'>
															<li>Ensure you have YAWM ModMii Edition installed in your Homebrew Channel</li>
															<li>Copy the downloaded WAD files to your SD card (recommended in a dedicated 'wad' folder)</li>
															<li>Have your Wii powered on and ready</li>
															<li>Make sure you have the correct WADs for your region</li>
														</ul>
													</div>

													{/* Recovery Information */}
													<div className='rounded-lg border border-red-700 bg-red-900/30 p-4'>
														<h4 className='mb-2 font-medium text-red-200'>🚨 Recovery Options:</h4>
														<ul className='ml-4 list-inside list-disc space-y-1 text-sm text-red-100'>
															<li><strong>BootMii:</strong> Can restore NAND backups if installed as boot2</li>
															<li><strong>Priiloader:</strong> Hold RESET while powering on to access recovery menu</li>
															<li><strong>Brick Recovery:</strong> Visit <Link href='https://wii.hacks.guide/bricks' className='text-blue-300 underline' target='_blank'>wii.hacks.guide/bricks</Link> for detailed recovery guides</li>
														</ul>
													</div>

													{/* Installation Tips */}
													<div className='rounded-lg border border-green-700 bg-green-900/30 p-4'>
														<h4 className='mb-2 font-medium text-green-200'>💡 Pro Tips:</h4>
														<ul className='ml-4 list-inside list-disc space-y-1 text-sm text-green-100'>
															<li>Install IOS files before cIOS files for best compatibility</li>
															<li>Take your time - rushing can lead to mistakes</li>
															<li>Double-check the WAD count before confirming installation</li>
															<li>Keep your SD card organized with a dedicated 'wad' folder</li>
															<li>Test your system after installation to ensure everything works</li>
														</ul>
													</div>
												</div>
											</DialogContent>
										</Dialog>

										<Button onClick={handleDownloadArchive} disabled={isCreatingArchive} size='sm' variant='outline'>
											<Archive className='mr-1 h-3 w-3' />
											{isCreatingArchive ? 'Creating...' : 'Download ZIP'}
										</Button>
									</div>
								</div>
								<div className='max-h-32 space-y-1 overflow-y-auto'>
									{uploadData.wadsInfos.map((file, index) => (
										<div key={index} className='flex items-center justify-between rounded bg-white p-2 shadow-sm'>
											<span className='font-mono text-xs text-gray-700'>{file.wadname}</span>
											<span className='text-xs text-gray-500'>{file.wadId}</span>
										</div>
									))}
								</div>
							</div>
						)}
					</div>
				)}
			</main>
		</div>
	);
}
